import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <UserButton
                userProfileProps={{
                  additionalOAuthScopes: {
                    google: [
                      "https://www.googleapis.com/auth/fitness.activity.read",
                      "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                      "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                      "https://www.googleapis.com/auth/fitness.body.read",
                      "https://www.googleapis.com/auth/fitness.heart_rate.read",
                      "https://www.googleapis.com/auth/fitness.body_temperature.read",
                      "https://www.googleapis.com/auth/fitness.location.read",
                      "https://www.googleapis.com/auth/fitness.nutrition.read",
                      "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                      "https://www.googleapis.com/auth/fitness.sleep.read"
                    ],
                  },
                }}
              />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}